-- Preload with 100 sample contacts
INSERT INTO contacts (id, name, phone, email, notes, created_at, updated_at, deleted_at) VALUES
(gen_random_uuid(), 'Alice Johnson', '+1-555-0101', 'alice.johnson@email.com', 'Friend from college', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
(gen_random_uuid(), 'Bob Smith', '+1-555-0102', 'bob.smith@email.com', 'Work colleague', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
(gen_random_uuid(), 'Carol Williams', '+1-555-0103', 'carol.w@email.com', 'Neighbor', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
(gen_random_uuid(), 'David Brown', '+1-555-0104', 'david.brown@email.com', 'Gym buddy', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
(gen_random_uuid(), 'Emma Davis', '+1-555-0105', 'emma.davis@email.com', 'Book club member', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
(gen_random_uuid(), 'Frank Miller', '+1-555-0106', 'frank.miller@email.com', 'Dad''s friend', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
(gen_random_uuid(), 'Grace Wilson', '+1-555-0107', 'grace.w@email.com', 'Yoga instructor', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
(gen_random_uuid(), 'Henry Moore', '+1-555-0108', 'henry.moore@email.com', 'Client', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
(gen_random_uuid(), 'Ivy Taylor', '+1-555-0109', 'ivy.taylor@email.com', 'Cousin', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
(gen_random_uuid(), 'Jack Anderson', '+1-555-0110', 'jack.a@email.com', 'Roommate', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
(gen_random_uuid(), 'Karen Thomas', '+1-555-0111', 'karen.thomas@email.com', 'Doctor', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
(gen_random_uuid(), 'Larry Jackson', '+1-555-0112', 'larry.j@email.com', 'Plumber', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
(gen_random_uuid(), 'Maria White', '+1-555-0113', 'maria.white@email.com', 'Hairdresser', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
(gen_random_uuid(), 'Nathan Harris', '+1-555-0114', 'nathan.h@email.com', 'Dentist', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
(gen_random_uuid(), 'Olivia Martin', '+1-555-0115', 'olivia.m@email.com', 'Sister-in-law', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
(gen_random_uuid(), 'Paul Thompson', '+1-555-0116', 'paul.t@email.com', 'Boss', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
(gen_random_uuid(), 'Quinn Garcia', '+1-555-0117', 'quinn.garcia@email.com', 'Marketing team', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
(gen_random_uuid(), 'Rachel Martinez', '+1-555-0118', 'rachel.m@email.com', 'HR manager', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
(gen_random_uuid(), 'Steve Robinson', '+1-555-0119', 'steve.r@email.com', 'IT support', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
(gen_random_uuid(), 'Tina Clark', '+1-555-0120', 'tina.c@email.com', 'Accountant', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
(gen_random_uuid(), 'Uma Rodriguez', '+1-555-0121', 'uma.r@email.com', 'Lawyer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
(gen_random_uuid(), 'Victor Lewis', '+1-555-0122', 'victor.l@email.com', 'Realtor', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
(gen_random_uuid(), 'Wendy Lee', '+1-555-0123', 'wendy.lee@email.com', 'Insurance agent', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
(gen_random_uuid(), 'Xavier Walker', '+1-555-0124', 'xavier.w@email.com', 'Personal trainer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
(gen_random_uuid(), 'Yara Hall', '+1-555-0125', 'yara.hall@email.com', 'Nurse', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
(gen_random_uuid(), 'Zack Allen', '+1-555-0126', 'zack.allen@email.com', 'Barber', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
(gen_random_uuid(), 'Amy Young', '+1-555-0127', 'amy.young@email.com', 'Pharmacist', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
(gen_random_uuid(), 'Ben Hernandez', '+1-555-0128', 'ben.h@email.com', 'Electrician', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
(gen_random_uuid(), 'Cindy King', '+1-555-0129', 'cindy.king@email.com', 'Veterinarian', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
(gen_random_uuid(), 'Dan Wright', '+1-555-0130', 'dan.wright@email.com', 'Carpenter', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
(gen_random_uuid(), 'Eva Lopez', '+1-555-0131', 'eva.lopez@email.com', 'Teacher', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
(gen_random_uuid(), 'Fred Hill', '+1-555-0132', 'fred.hill@email.com', 'Mechanic', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
(gen_random_uuid(), 'Gina Scott', '+1-555-0133', 'gina.scott@email.com', 'Photographer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
(gen_random_uuid(), 'Hank Green', '+1-555-0134', 'hank.green@email.com', 'Chef', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
(gen_random_uuid(), 'Iris Adams', '+1-555-0135', 'iris.adams@email.com', 'Artist', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
(gen_random_uuid(), 'Joe Baker', '+1-555-0136', 'joe.baker@email.com', 'Musician', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
(gen_random_uuid(), 'Kate Nelson', '+1-555-0137', 'kate.nelson@email.com', 'Writer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
(gen_random_uuid(), 'Leo Carter', '+1-555-0138', 'leo.carter@email.com', 'Developer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
(gen_random_uuid(), 'Mia Mitchell', '+1-555-0139', 'mia.m@email.com', 'Designer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
(gen_random_uuid(), 'Nick Perez', '+1-555-0140', 'nick.perez@email.com', 'Architect', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
(gen_random_uuid(), 'Ora Roberts', '+1-555-0141', 'ora.roberts@email.com', 'Consultant', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
(gen_random_uuid(), 'Pete Turner', '+1-555-0142', 'pete.t@email.com', 'Analyst', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
(gen_random_uuid(), 'Quincy Phillips', '+1-555-0143', 'quincy.p@email.com', 'Manager', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
(gen_random_uuid(), 'Rita Campbell', '+1-555-0144', 'rita.c@email.com', 'Professor', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
(gen_random_uuid(), 'Sam Parker', '+1-555-0145', 'sam.parker@email.com', 'Student', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
(gen_random_uuid(), 'Tara Evans', '+1-555-0146', 'tara.evans@email.com', 'Researcher', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
(gen_random_uuid(), 'Ulrich Edwards', '+1-555-0147', 'ulrich.e@email.com', 'Scientist', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
(gen_random_uuid(), 'Vera Collins', '+1-555-0148', 'vera.collins@email.com', 'Journalist', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
(gen_random_uuid(), 'Will Stewart', '+1-555-0149', 'will.s@email.com', 'Filmmaker', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
(gen_random_uuid(), 'Xena Sanchez', '+1-555-0150', 'xena.s@email.com', 'Social worker', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
(gen_random_uuid(), 'Yuri Morris', '+1-555-0151', 'yuri.morris@email.com', 'Engineer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
(gen_random_uuid(), 'Zoe Rogers', '+1-555-0152', 'zoe.rogers@email.com', 'Therapist', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
(gen_random_uuid(), 'Adam Reed', '+1-555-0153', 'adam.reed@email.com', 'Contractor', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
(gen_random_uuid(), 'Bella Cook', '+1-555-0154', 'bella.cook@email.com', 'Interior designer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
(gen_random_uuid(), 'Carl Morgan', '+1-555-0155', 'carl.morgan@email.com', 'Financial advisor', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
(gen_random_uuid(), 'Dora Bell', '+1-555-0156', 'dora.bell@email.com', 'Event planner', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
(gen_random_uuid(), 'Ethan Murphy', '+1-555-0157', 'ethan.m@email.com', 'Sales representative', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
(gen_random_uuid(), 'Fiona Bailey', '+1-555-0158', 'fiona.b@email.com', 'Customer service', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
(gen_random_uuid(), 'Greg Rivera', '+1-555-0159', 'greg.rivera@email.com', 'Operations manager', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
(gen_random_uuid(), 'Holly Cooper', '+1-555-0160', 'holly.c@email.com', 'HR coordinator', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
(gen_random_uuid(), 'Ivan Richardson', '+1-555-0161', 'ivan.r@email.com', 'Logistics', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
(gen_random_uuid(), 'Jade Cox', '+1-555-0162', 'jade.cox@email.com', 'Quality assurance', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
(gen_random_uuid(), 'Kevin Howard', '+1-555-0163', 'kevin.h@email.com', 'Procurement', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
(gen_random_uuid(), 'Luna Ward', '+1-555-0164', 'luna.ward@email.com', 'Supply chain', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
(gen_random_uuid(), 'Mark Torres', '+1-555-0165', 'mark.torres@email.com', 'Business analyst', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
(gen_random_uuid(), 'Nina Peterson', '+1-555-0166', 'nina.p@email.com', 'Product manager', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
(gen_random_uuid(), 'Owen Gray', '+1-555-0167', 'owen.gray@email.com', 'UX researcher', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
(gen_random_uuid(), 'Pam Ramirez', '+1-555-0168', 'pam.ramirez@email.com', 'Content writer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
(gen_random_uuid(), 'Quentin James', '+1-555-0169', 'quentin.j@email.com', 'Data scientist', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
(gen_random_uuid(), 'Rosa Watson', '+1-555-0170', 'rosa.w@email.com', 'Marketing director', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
(gen_random_uuid(), 'Sean Brooks', '+1-555-0171', 'sean.brooks@email.com', 'SEO specialist', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
(gen_random_uuid(), 'Tess Kelly', '+1-555-0172', 'tess.kelly@email.com', 'Brand manager', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
(gen_random_uuid(), 'Umar Sanders', '+1-555-0173', 'umar.s@email.com', 'Web developer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
(gen_random_uuid(), 'Vicky Price', '+1-555-0174', 'vicky.price@email.com', 'Mobile developer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
(gen_random_uuid(), 'Wade Bennett', '+1-555-0175', 'wade.b@email.com', 'DevOps engineer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
(gen_random_uuid(), 'Ximena Wood', '+1-555-0176', 'ximena.wood@email.com', 'Cloud architect', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
(gen_random_uuid(), 'Yale Barnes', '+1-555-0177', 'yale.barnes@email.com', 'Security analyst', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
(gen_random_uuid(), 'Zara Ross', '+1-555-0178', 'zara.ross@email.com', 'QA engineer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
(gen_random_uuid(), 'Axel Henderson', '+1-555-0179', 'axel.h@email.com', 'Technical lead', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
(gen_random_uuid(), 'Bree Coleman', '+1-555-0180', 'bree.c@email.com', 'Scrum master', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
(gen_random_uuid(), 'Chad Jenkins', '+1-555-0181', 'chad.j@email.com', 'Agile coach', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
(gen_random_uuid(), 'Dawn Perry', '+1-555-0182', 'dawn.perry@email.com', 'Tech recruiter', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
(gen_random_uuid(), 'Eli Powell', '+1-555-0183', 'eli.powell@email.com', 'Startup founder', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
(gen_random_uuid(), 'Fawn Long', '+1-555-0184', 'fawn.long@email.com', 'Venture capitalist', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
(gen_random_uuid(), 'Glen Patterson', '+1-555-0185', 'glen.p@email.com', 'Angel investor', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
(gen_random_uuid(), 'Hope Hughes', '+1-555-0186', 'hope.hughes@email.com', 'Business coach', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
(gen_random_uuid(), 'Ian Flores', '+1-555-0187', 'ian.flores@email.com', 'Life coach', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
(gen_random_uuid(), 'Jill Washington', '+1-555-0188', 'jill.w@email.com', 'Career counselor', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
(gen_random_uuid(), 'Kurt Butler', '+1-555-0189', 'kurt.butler@email.com', 'Motivational speaker', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
(gen_random_uuid(), 'Lila Simmons', '+1-555-0190', 'lila.s@email.com', 'Leadership trainer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
(gen_random_uuid(), 'Matt Foster', '+1-555-0191', 'matt.foster@email.com', 'Team building facilitator', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
(gen_random_uuid(), 'Nora Gonzales', '+1-555-0192', 'nora.g@email.com', 'Mediator', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
(gen_random_uuid(), 'Otto Bryant', '+1-555-0193', 'otto.bryant@email.com', 'Negotiator', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
(gen_random_uuid(), 'Pia Alexander', '+1-555-0194', 'pia.a@email.com', 'Public speaker', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
(gen_random_uuid(), 'Quin Russell', '+1-555-0195', 'quin.russell@email.com', 'Presentation coach', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
(gen_random_uuid(), 'Rory Griffin', '+1-555-0196', 'rory.griffin@email.com', 'Communication expert', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
(gen_random_uuid(), 'Sandy Diaz', '+1-555-0197', 'sandy.diaz@email.com', 'Storyteller', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
(gen_random_uuid(), 'Todd Hayes', '+1-555-0198', 'todd.hayes@email.com', 'Mentor', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
(gen_random_uuid(), 'Unity Myers', '+1-555-0199', 'unity.myers@email.com', 'Life mentor', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
(gen_random_uuid(), 'Vance Ford', '+1-555-0200', 'vance.ford@email.com', 'Career mentor', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
